### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by GoldeggCoder** [asukiaaa/esp32-client-for-xbox-controller-with-nim-ble#1]
Is there any docs about what button or stick changes which value? Great project. Keep the work up!

**Comment by asukiaaa** [comment]
This project was practice to make a library https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32 to handle https://github.com/asukiaaa/arduino-XboxControllerNotificationParser and https://github.com/asukiaaa/arduino-XboxSeriesXHIDReportBuilder .
Use first library on ESP32.
